// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnxf7nN8eOu0d6gzuG9Ohy-xxtL7JuoM',
    appId: '1:588105156965:web:d67167036c61a551a2b98c',
    messagingSenderId: '588105156965',
    projectId: 'eytechathon-f9725',
    authDomain: 'eytechathon-f9725.firebaseapp.com',
    storageBucket: 'eytechathon-f9725.firebasestorage.app',
    measurementId: 'G-SSHML13V3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyWePq8eaebv3R-DlBEO2nkqlVJpej8U',
    appId: '1:588105156965:android:424b7029a7d11ef8a2b98c',
    messagingSenderId: '588105156965',
    projectId: 'eytechathon-f9725',
    storageBucket: 'eytechathon-f9725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPyyzxTv56RdsSCTLJdg1Jnq7tsUjF54',
    appId: '1:588105156965:ios:a000ffad4baf2e15a2b98c',
    messagingSenderId: '588105156965',
    projectId: 'eytechathon-f9725',
    storageBucket: 'eytechathon-f9725.firebasestorage.app',
    iosBundleId: 'com.example.eyTechathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPyyzxTv56RdsSCTLJdg1Jnq7tsUjF54',
    appId: '1:588105156965:ios:a000ffad4baf2e15a2b98c',
    messagingSenderId: '588105156965',
    projectId: 'eytechathon-f9725',
    storageBucket: 'eytechathon-f9725.firebasestorage.app',
    iosBundleId: 'com.example.eyTechathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqnxf7nN8eOu0d6gzuG9Ohy-xxtL7JuoM',
    appId: '1:588105156965:web:e473510a75d69c8ca2b98c',
    messagingSenderId: '588105156965',
    projectId: 'eytechathon-f9725',
    authDomain: 'eytechathon-f9725.firebaseapp.com',
    storageBucket: 'eytechathon-f9725.firebasestorage.app',
    measurementId: 'G-TFZGKYNZXN',
  );
}
